"""empty message

Revision ID: 1ffdc1717497
Revises: 68aae8f9201c
Create Date: 2022-04-16 15:01:18.013833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ffdc1717497'
down_revision = '68aae8f9201c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
