"""empty message

Revision ID: 25a441086bfb
Revises: 01c9dae0f6c7
Create Date: 2022-04-16 15:04:23.605776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25a441086bfb'
down_revision = '01c9dae0f6c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
