"""empty message

Revision ID: 32e399a24120
Revises: 25a441086bfb
Create Date: 2022-04-16 15:05:27.531873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32e399a24120'
down_revision = '25a441086bfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
