"""empty message

Revision ID: 453bcfb0616f
Revises: 32e399a24120
Create Date: 2022-04-16 15:58:36.884016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '453bcfb0616f'
down_revision = '32e399a24120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
