"""empty message

Revision ID: 47772eebc191
Revises: 1ffdc1717497
Create Date: 2022-04-16 15:01:49.526274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47772eebc191'
down_revision = '1ffdc1717497'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
