"""empty message

Revision ID: 68aae8f9201c
Revises: 
Create Date: 2022-04-16 14:52:04.169686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68aae8f9201c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platforms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('windows', sa.Boolean(), nullable=True),
    sa.Column('mac', sa.Boolean(), nullable=True),
    sa.Column('linux', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('vanity_username', sa.String(), nullable=True),
    sa.Column('steamid', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('steamid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('steam_app_details',
    sa.Column('steam_appid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('is_free', sa.Boolean(), nullable=True),
    sa.Column('about_the_game', sa.String(), nullable=True),
    sa.Column('header_image', sa.String(), nullable=True),
    sa.Column('platforms_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['platforms_id'], ['platforms.id'], ),
    sa.PrimaryKeyConstraint('steam_appid'),
    sa.UniqueConstraint('steam_appid')
    )
    op.create_table('steam_apps',
    sa.Column('appid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('appid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('steam_apps')
    op.drop_table('steam_app_details')
    op.drop_table('users')
    op.drop_table('platforms')
    # ### end Alembic commands ###
